# Generated by Django 3.0.8 on 2020-07-21 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=64)),
                ('txt', models.CharField(max_length=6400)),
                ('tmt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
