# Generated by Django 3.0.8 on 2020-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrs', models.CharField(max_length=64)),
                ('following', models.CharField(blank=True, max_length=64, null=True)),
                ('followers', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
