# Generated by Django 3.0.8 on 2020-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=64)),
                ('pid', models.IntegerField()),
                ('by', models.CharField(max_length=64)),
            ],
        ),
    ]
